sonar.projectKey=diazdesandi_thaw-raycast
sonar.organization=diazdesandi
sonar.projectName=thaw-raycast
sonar.projectVersion=1.0 # Update this to the current version

sonar.sources=src

sonar.exclusions=**/node_modules/**, **/assets/**, **/metadata/**, **/dist/**, **/build/**, **/*.json, **/*.md
sonar.cpd.exclusions=eslint.config.js, .prettierrc

sonar.javascript.node.maxspace=4096
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8

# Test paths
# sonar.tests=tests
# sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
